# Exercise 1 

In this exercise, we will work with the `spam.csv` data file. This file contains text and a label attached to each text. The goal is to clean the text data and then build classifcation models. 

### Exercise 1(a) (2 points)

Load the `pandas` and `numpy` libraries.

In [2]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `spam_df`.

In [3]:
spam_df = pd.read_csv("spam.csv")
spam_df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Exercise 1(c) (2 points)

Using the `string` library, remove all the punctuation of the `text` column.

In [4]:
import string

spam_df ["text_clean"] = spam_df["text"].str.replace(f"[{string.punctuation}]", "", regex=True)
spam_df.head()

,label,text,text_clean
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...

### Exercise 1(d) (10 points)

Using the `nltk` library, remove stopwords and pronouns from `text_clean` and store in another column called `'text_clean_1'`.

In [5]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
pronouns = ["i", "me", "my", "mine", "we", "us", "our", "ours", "you", "your", "yours", "he", "him", "his", "she", "her", "hers", "they", "them", "their", "theirs", "u", "ur", "urs", "im", "dont", "2" , "ill", "4"]


def clean_text(text):
    # Tokenize the text
    tokens = word_tokenize(text.lower())
    
     # replacing words
    tokens = [word.replace ('txt', 'text') for word in tokens]
    # remove stopwords and pronouns
    tokens = [word for word in tokens if word not in stop_words and word not in pronouns]

    return ' '.join(tokens)

spam_df['text_clean_1'] = spam_df['text'].apply(clean_text)
spam_df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\juani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\juani\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,label,text,text_clean,text_clean_1
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,"go jurong point , crazy .. available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar ... joking wif oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor ... c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"nah n't think goes usf , lives around though"

### Exercise 1(e) (10 points)

Perform Lemmatization of `text_clean_1` and store the results in another column called `text_clean_2` in the `spam_df` data frame.

In [6]:
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]
    return ' '.join(lemmatized_tokens)

spam_df['text_clean_2'] = spam_df['text_clean_1'].apply(lemmatize_text)
spam_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\juani\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\juani\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,label,text,text_clean,text_clean_1,text_clean_2
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,"go jurong point , crazy .. available bugis n g...","go jurong point , crazy .. available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar ... joking wif oni ...,ok lar ... joking wif oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor ... c already say ...,dun say early hor ... c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"nah n't think goes usf , lives around though","nah n't think go usf , life around though"

### Exercise 1(f) (5 points)

Based on the results from part 1(f), we see digits in some of the text in `text_clean_2`. Remove all the digits from `text_clean_2` and store the results in another column `text_clean_3` in the `spam_df` data frame.

In [7]:
import re

# function to remove numbers from text
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

spam_df['text_clean_3'] = spam_df['text_clean_2'].apply(remove_numbers)
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,"go jurong point , crazy .. available bugis n g...","go jurong point , crazy .. available bugis n g...","go jurong point , crazy .. available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar ... joking wif oni ...,ok lar ... joking wif oni ...,ok lar ... joking wif oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor ... c already say ...,dun say early hor ... c already say ...,dun say early hor ... c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"nah n't think goes usf , lives around though","nah n't think go usf , life around though","nah n't think go usf , life around though"

### Exercise 1(g) (5 points)

Generate topic features using BERT embeddings on `text_clean_3`.

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("Loading BERT model")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("BERT model loaded")

# generating the embeddings for the cleaned text
print("Generating embeddings..")
embeddings = bert_model.encode(spam_df['text_clean_3'].tolist(),
                               show_progress_bar=True,
                               batch_size=32)
print("Embeddings generated")
print(f"Embeddings shape: {embeddings.shape}")
print(f"Each document is represented by a {embeddings.shape[1]}-dimensional vector")

Loading BERT model

'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 1s [Retry 1/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 2s [Retry 2/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 4s [Retry 3/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 8s [Retry 4/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 8s [Retry 5/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Could not reach the Hub ([SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)). Using cached commit hash for 'sentence-transformers/all-MiniLM-L6-v2'.
Could not reach the Hub ([SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)). Using cached commit hash for 'sentence-transformers/all-MiniLM-L6-v2'.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2270.89it/s]
Could not reach the Hub ([SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)). Using cached commit hash for 'sentence-transformers/all-MiniLM-L6-v2'.
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json
Retrying in 1s [Retry 1/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json
Retrying in 2s [Retry 2/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json
Retrying in 4s [Retry 3/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json
Retrying in 8s [Retry 4/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json
Retrying in 8s [Retry 5/5].
'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json

BERT model loaded
Generating embeddings..

Batches: 100%|██████████| 175/175 [00:48<00:00,  3.58it/s]

Embeddings generated
Embeddings shape: (5572, 384)
Each document is represented by a 384-dimensional vector

### Exercise 1(h) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=3.

2. Assign the cluster labels to a new column in `spam_df` called `'kmeans_cluster_label'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_kmeans_features`.

In [11]:
from sklearn.preprocessing import normalize

#normalize the embeddings
embeddings_normalized = normalize(embeddings)

# apply Kmeans clustering on the normalized embeddings
num_cluster = 3

kmeans = KMeans(n_clusters=num_cluster, n_init=20, random_state=42)
kmeans.fit(embeddings_normalized)
labels = kmeans.labels_

# storing the cluster labels
spam_df['cluster'] =  kmeans.labels_

# compute the distance of each point to its assigned cluster center
X_kmeans_features = kmeans.transform(embeddings_normalized)

In [13]:
X_kmeans_features.shape

(5572, 3)

In [14]:
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3,cluster
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,"go jurong point , crazy .. available bugis n g...","go jurong point , crazy .. available bugis n g...","go jurong point , crazy .. available bugis n g...",2
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar ... joking wif oni ...,ok lar ... joking wif oni ...,ok lar ... joking wif oni ...,2
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...,1
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor ... c already say ...,dun say early hor ... c already say ...,dun say early hor ... c already say ...,2
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,"nah n't think goes usf , lives around though","nah n't think go usf , life around though","nah n't think go usf , life around though",0

### Exercise 1(i) (5 points)

Hierarchical clustering is a type of density-based grouping used to organize documents based on similarity.

1. Apply Agglomerative Hierarchical Clustering to the L2​-normalized BERT embeddings (bert_embeddings) with k=3 clusters, using the `'ward'` linkage method.

2. Store the resulting cluster assignments in a new column called `'bert_hierarchical_label'` in `spam_df`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_hierarchical_features`.

In [17]:
from sklearn.cluster import AgglomerativeClustering

#applying agglormative clustering on the normalized embeddings

num_cluster = 3
agg_clustering = AgglomerativeClustering(n_clusters=num_cluster, linkage='ward')
spam_df['bert_hierarchical_label'] = agg_clustering.fit_predict(embeddings_normalized)
print(spam_df[['bert_hierarchical_label']].head())

   bert_hierarchical_label
0                        0
1                        0
2                        2
3                        0
4                        0

In [24]:
from sklearn.metrics.pairwise import euclidean_distances

# compute the centroids mannually
centroids = []
for i in range(num_cluster):
    centroids.append(embeddings_normalized[spam_df['bert_hierarchical_label'] == i].mean(axis=0))
centroids = np.array(centroids)

# compute distance to the centroids
X_hierarchical_features = euclidean_distances(embeddings_normalized, centroids)

In [25]:
X_hierarchical_features

array([[0.88779783, 0.94456244, 1.0460417 ],
       [0.8950131 , 0.98003596, 1.153106  ],
       [0.9411652 , 0.88414156, 0.85705495],
       ...,
       [0.91815734, 1.0025346 , 1.1361082 ],
       [0.9542542 , 0.9580698 , 1.0118008 ],
       [0.917422  , 1.009049  , 1.13791   ]],
      shape=(5572, 3), dtype=float32)

### Exercise 1(j) (10 points)

Train and evaluate six `LogisticRegression` models as follows:

- Using `kmeans` features as input.
- Using `hierarchical` features as input.
- Using bert embedding features as input.
- Combining `kmeans` + bert embeddings features as input.
- Combining `hierarchical` + bert embeddings features as input.
- Combining `kmeans` + `hierarchical` + bert embeddings features as input.

Evaluate the six models over a five-fold cross validation strategy.

In [28]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

y = spam_df['label'].map({'ham': 0, 'spam': 1})

# first input
X_kmeans = X_kmeans_features


# second input
X_hierarchical = X_hierarchical_features

#third input
X_third = embeddings

#Fourt input
X_fourth = np.hstack([X_kmeans , embeddings])

#Fifth input
X_fifth = np.hstack([X_hierarchical , embeddings])

#Sixth input
X_sixth = np.hstack([X_kmeans , X_hierarchical , embeddings])

print("comparing classification performance of different input combinations")
print("="*60)

model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))

# evulation each feature set

feature_sets = {
    "First input" : X_kmeans,
    "Second input" : X_hierarchical,
    "Third input" : X_third,
    "Fourth input" : X_fourth,
    "Fifth input" : X_fifth,
    "Sixth input" : X_sixth
}

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))
    results[name] = (scores.mean(), scores.std())
    print(f"{name}: Mean Accuracy = {scores.mean():.4f}, Std = {scores.std():.4f}")

print("\nSummary of results:")
for name, (mean, std) in results.items():
    print(f"{name}: Mean Accuracy = {mean:.4f}, Std = {std:.4f}")

#finding the best performaing feature set
best_feature_set = max(results, key=lambda k: results[k][0])
print(f"\nBest performing feature set: {best_feature_set} with Mean Accuracy = {results[best_feature_set][0]:.4f}, Std = {results[best_feature_set][1]:.4f}")

comparing classification performance of different input combinations
============================================================
First input: Mean Accuracy = 0.9250, Std = 0.0051
Second input: Mean Accuracy = 0.9309, Std = 0.0058
Third input: Mean Accuracy = 0.9779, Std = 0.0024
Fourth input: Mean Accuracy = 0.9777, Std = 0.0022
Fifth input: Mean Accuracy = 0.9785, Std = 0.0015
Sixth input: Mean Accuracy = 0.9781, Std = 0.0022

Summary of results:
First input: Mean Accuracy = 0.9250, Std = 0.0051
Second input: Mean Accuracy = 0.9309, Std = 0.0058
Third input: Mean Accuracy = 0.9779, Std = 0.0024
Fourth input: Mean Accuracy = 0.9777, Std = 0.0022
Fifth input: Mean Accuracy = 0.9785, Std = 0.0015
Sixth input: Mean Accuracy = 0.9781, Std = 0.0022

Best performing feature set: Fifth input with Mean Accuracy = 0.9785, Std = 0.0015